#!/usr/bin/env python3
"""Generate a browsable HTML gallery of all pi.dev sessions.

Scans ~/.pi/agent/sessions/, ingests sessions with ≥N prompts into a single
SQLite DB, labels with stub, and generates:
  - session-view JSON + embedded HTML for each session
  - index.html — a browsable gallery with links to each session

Usage:
    python scripts/gen_session_gallery.py                      # all repos, ≥3 prompts
    python scripts/gen_session_gallery.py --repo kuchnie       # filter by repo
    python scripts/gen_session_gallery.py --min-prompts 5      # only rich sessions
    python scripts/gen_session_gallery.py --top 10             # top 10 by score
    python scripts/gen_session_gallery.py --out ./gallery      # output directory
"""

from __future__ import annotations

import argparse
import json
import sqlite3
import sys
import tempfile
from pathlib import Path

# Add scripts dir to path for imports
sys.path.insert(0, str(Path(__file__).parent))
from scan_sessions import scan_all_sessions
from gen_session_view import generate as gen_view


def _ingest_session(conn: sqlite3.Connection, session_path: Path) -> int | None:
    """Ingest a pi session file, return chat_id or None on failure."""
    from git_llm import ingest as ingest_mod
    from git_llm import db as db_mod
    try:
        db_mod.init_schema(conn)
        chat_id = ingest_mod.ingest_file(conn, session_path)
        conn.commit()
        return chat_id
    except Exception as e:
        print(f"    ⚠ ingest failed: {e}", file=sys.stderr)
        conn.rollback()
        return None


def _label_stub(conn: sqlite3.Connection, chat_id: int) -> int:
    """Label all turns with stub labeler."""
    from git_llm.label import StubLabeler, label_chat
    return label_chat(conn, chat_id, StubLabeler())


def _build_index(sessions: list[dict], out_dir: Path) -> None:
    """Generate index.html gallery page."""
    cards_html = ""
    for s in sessions:
        slug = s["slug"]
        score = s["score"]
        color = "#059669" if score >= 80 else ("#d97706" if score >= 60 else "#9ca3af")
        cards_html += f"""
        <a href="{slug}.html" class="card" style="border-left: 3px solid {color}">
            <div class="card-header">
                <span class="repo">{s['repo']}</span>
                <span class="score" style="color:{color}">{score:.0f}</span>
            </div>
            <div class="card-meta">{s['prompts']} prompts · {s['turns']} turns · {s['phases']} phases</div>
            <div class="card-title">{s['title']}</div>
        </a>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Session Gallery — git-llm</title>
<style>
* {{ box-sizing: border-box; margin: 0; padding: 0; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
  background: #f8f9fa; color: #1a1a2e; padding: 32px; }}
h1 {{ font-size: 24px; margin-bottom: 8px; }}
.subtitle {{ color: #6b7280; font-size: 14px; margin-bottom: 24px; }}
.grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(320px, 1fr)); gap: 16px; }}
.card {{ background: #fff; border: 1px solid #e5e7eb; border-radius: 8px;
  padding: 16px; text-decoration: none; color: inherit; transition: all 0.15s;
  box-shadow: 0 1px 3px rgba(0,0,0,0.04); }}
.card:hover {{ box-shadow: 0 4px 12px rgba(0,0,0,0.1); transform: translateY(-2px); }}
.card-header {{ display: flex; justify-content: space-between; align-items: center;
  margin-bottom: 8px; }}
.repo {{ font-size: 12px; font-weight: 600; text-transform: uppercase;
  letter-spacing: 0.05em; color: #6b7280; }}
.score {{ font-size: 20px; font-weight: 700; }}
.card-meta {{ font-size: 12px; color: #9ca3af; margin-bottom: 6px; }}
.card-title {{ font-size: 14px; color: #374151; line-height: 1.4; }}
.legend {{ display: flex; gap: 16px; margin-bottom: 24px; font-size: 12px; color: #6b7280; }}
.legend span {{ display: flex; align-items: center; gap: 4px; }}
.dot {{ width: 8px; height: 8px; border-radius: 50%; }}
</style>
</head>
<body>
<h1>🗂️ Session Gallery</h1>
<p class="subtitle">{len(sessions)} sessions · generated by git-llm</p>
<div class="legend">
  <span><span class="dot" style="background:#059669"></span> Score ≥ 80</span>
  <span><span class="dot" style="background:#d97706"></span> Score 60–79</span>
  <span><span class="dot" style="background:#9ca3af"></span> Score &lt; 60</span>
</div>
<div class="grid">{cards_html}
</div>
</body>
</html>"""

    (out_dir / "index.html").write_text(html, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate session gallery")
    parser.add_argument("--repo", help="Filter by repo name substring")
    parser.add_argument("--min-prompts", type=int, default=3)
    parser.add_argument("--top", type=int, default=20)
    parser.add_argument("--out", default="gallery", help="Output directory")
    parser.add_argument("--sessions-dir", type=Path, default=None)
    args = parser.parse_args()

    sessions_dir = args.sessions_dir or Path.home() / ".pi" / "agent" / "sessions"
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    # 1. Scan sessions
    print(f"Scanning sessions...", file=sys.stderr)
    metrics = scan_all_sessions(sessions_dir, args.repo)
    metrics = [m for m in metrics if m.user_prompts >= args.min_prompts]
    metrics = metrics[: args.top]
    print(f"Found {len(metrics)} sessions (≥{args.min_prompts} prompts, top {args.top})", file=sys.stderr)

    # 2. Ingest into a single DB
    db_path = out_dir / "gallery.sqlite"
    if db_path.exists():
        db_path.unlink()
    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row

    gallery_entries = []

    for i, m in enumerate(metrics, 1):
        slug = f"{m.repo}-{m.session_id[:8]}"
        print(f"\n[{i}/{len(metrics)}] {m.repo}/{m.session_id[:8]} ({m.user_prompts} prompts)", file=sys.stderr)

        # Ingest
        chat_id = _ingest_session(conn, m.path)
        if chat_id is None:
            continue

        # Label with stub
        n_labels = _label_stub(conn, chat_id)
        print(f"    ingested chat_id={chat_id}, labeled {n_labels}", file=sys.stderr)

        # Generate JSON
        try:
            data = generate(str(db_path), chat_id)
        except Exception as e:
            print(f"    ⚠ view generation failed: {e}", file=sys.stderr)
            continue

        json_path = out_dir / f"{slug}.json"
        json_path.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")

        # Generate embedded HTML
        html_template = Path("docs/evaluation/session-view.html")
        if html_template.exists():
            html = html_template.read_text(encoding="utf-8")
            json_str = json.dumps(data, ensure_ascii=False)
            embed_tag = f'<script id="session-data" type="application/json">{json_str}</script>'
            html = html.replace("</body>", f"{embed_tag}\n</body>")
            html_path = out_dir / f"{slug}.html"
            html_path.write_text(html, encoding="utf-8")
            print(f"    → {html_path.name} ({html_path.stat().st_size // 1024}K)", file=sys.stderr)

        gallery_entries.append({
            "slug": slug,
            "repo": m.repo,
            "title": m.user_text[0][:60] if m.user_text else f"Session {m.session_id[:8]}",
            "prompts": m.user_prompts,
            "turns": data["meta"]["turn_count"],
            "phases": len(data["phases"]),
            "score": m.meta_score,
        })

    conn.close()

    # 3. Generate index
    _build_index(gallery_entries, out_dir)
    print(f"\n✓ Gallery: {out_dir}/index.html ({len(gallery_entries)} sessions)", file=sys.stderr)


# Re-export generate from gen_session_view
def generate(db_path: str, chat_id: int) -> dict:
    return gen_view(db_path, chat_id)


if __name__ == "__main__":
    main()
